# Generated by Django 2.2.1 on 2019-05-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('B3_BRL_WIN', 'WIN')], default='B3_BRL_WIN', max_length=50)),
                ('timeframe', models.SmallIntegerField(choices=[(0, '----'), (1, 'M1'), (2, 'M2'), (3, 'M3'), (5, 'M5'), (15, 'M15'), (60, 'H1'), (1440, 'D1'), (10080, 'W1')], default=0)),
                ('market_cycle', models.SmallIntegerField(choices=[(1, 'BO - Breakout'), (3, 'TC - Tight Channel'), (3, 'BC - Broad Channel'), (4, 'TR - Trading Range'), (5, 'TTR - Tight Trading Range')], default=0)),
                ('optype', models.SmallIntegerField(choices=[(0, '----'), (1, 'Scalp'), (2, 'Swing')], default=0)),
                ('duration', models.SmallIntegerField(choices=[(1, 'Day Trade'), (2, 'Swing Trade'), (3, 'Position Trade')], default=1)),
                ('open_price', models.FloatField(null=True)),
                ('open_time', models.DateTimeField(null=True)),
                ('is_open_correct', models.BooleanField(default=True)),
                ('close_price', models.FloatField(null=True)),
                ('close_time', models.DateTimeField(null=True)),
                ('is_close_correct', models.BooleanField(default=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ordem de abertura pendurada'), (2, 'Operação aberta'), (3, 'Ordem de encerramento pendurada'), (4, 'Operação encerrada')], default=1)),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.Strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
