# Generated by Django 2.2.1 on 2019-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_acctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='timeframe',
            field=models.SmallIntegerField(choices=[(0, '----'), (1, 'M1'), (2, 'M2'), (3, 'M3'), (5, 'M5'), (15, 'M15'), (60, 'H1'), (1440, 'D1'), (10080, 'W1')], default=5),
        ),
    ]
