# Generated by Django 2.2.1 on 2019-06-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20190603_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_conduction_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_price',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
