# Generated by Django 2.2.1 on 2019-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_auto_20190603_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='user',
        ),
        migrations.AddField(
            model_name='trade',
            name='close_error',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='conduction_error',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_error',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trade',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(default='WIN', max_length=50),
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
