# Generated by Django 2.2.1 on 2019-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20190603_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='open_time',
        ),
    ]
