# Generated by Django 2.2.1 on 2019-06-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_trade_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Operação aberta'), (2, 'Operação encerrada')], default=1),
        ),
    ]
