# Generated by Django 2.2.1 on 2019-06-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_auto_20190603_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='picture',
            new_name='image',
        ),
    ]
