# Generated by Django 2.2.1 on 2019-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_auto_20190603_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='result',
            field=models.SmallIntegerField(choices=[(0, '--'), (1, 'GAIN'), (2, 'LOSS'), (3, 'BREAK EVEN')], default=0),
        ),
    ]
