# Generated by Django 2.2.1 on 2019-06-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20190610_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
