# Generated by Django 2.2.1 on 2019-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_trade_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
