# Generated by Django 2.2.1 on 2019-06-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_auto_20190610_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='is_close_correct',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='is_conduction_correct',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='is_open_correct',
        ),
        migrations.AddField(
            model_name='trade',
            name='is_market_interpretation_correct_at_open',
            field=models.BooleanField(default=False),
        ),
    ]
