# Generated by Django 2.2.1 on 2019-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0019_trade_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeerrors',
            name='related_to',
            field=models.SmallIntegerField(choices=[(0, '--'), (1, 'Abertura da operação'), (3, 'Condução da operação'), (2, 'Fechamento da operação')], default=0),
        ),
    ]
